---
title: "Economic Connectedness"
description: |
  Welcome to the website. I hope you enjoy it!
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
```


```{r, clean_data}
#Specific columns in the direct data sets are yet to be selected. This is unlike the previously given ec.rds file, which had pre-filtered out the columns from the direct data set for a cleaner look at the data for us.
ec <- read_rds(file = "clean_data.rds")
```


```{r}
# Look at missing data later.
ec |> 
  ggplot(aes(x = pop2018, y = ec_county)) +
    geom_point() +
    geom_smooth(method = "lm", formula = y ~ x, se = FALSE) +
    scale_x_log10(breaks = c(1000, 10000, 1000000),
                  labels = c("1,000", "10,000", "1,000,0000")) +
    labs(y = "Economic Connectedness",
         x = "Population",
         title = "Economic Connectedness and Population in US Counties",
         subtitle = "There is no relationship between population and economic connectedness in US counties.")
  
```


```{r}
ec |> 
  group_by(state) |> 
  summarise(pop_state = sum(pop2018),
            avg_ec = mean(ec_county)) |> 
  ggplot(aes(x = pop_state, y = avg_ec)) +
    geom_point() +
    geom_smooth(method = "lm", formula = y ~ x, se = FALSE) +
    scale_x_log10(breaks = c(1000000, 10000000),
                  labels = c("1,000,0000", "10,000,000")) +
    labs(y = "Average County Economic Connectedness",
         x = "State Population",
         title = "Economic Connectedness and Population in US States",
         subtitle = "Biggger states have counties with lower average economic connectedness.")

```
